# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_global.ui'
# Hand-translated for modern Anki (Qt6/Qt5 compat via aqt.qt)

from aqt.qt import (
    QDialog, QVBoxLayout, QGridLayout, QTabWidget, QWidget,
    QLabel, QSpinBox, QCheckBox, QLineEdit, QTextBrowser,
    QDialogButtonBox, QSizePolicy, Qt
)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setWindowTitle("Cloze Overlapper Options")
        Dialog.resize(421, 500)
        Dialog.setSizePolicy(QSizePolicy.Policy.MinimumExpanding,
                             QSizePolicy.Policy.MinimumExpanding)

        self.verticalLayout = QVBoxLayout(Dialog)

        self.tabWidget = QTabWidget(Dialog)

        # Tab 1: Cloze Generation
        self.tab = QWidget()
        tab1_layout = QVBoxLayout(self.tab)

        # Default Context Cues and Prompts
        grid1 = QGridLayout()
        grid1.addWidget(QLabel("<b>Default Context Cues and Prompts</b>"), 0, 0, 1, 3)

        lbl_before = QLabel("Context Before")
        lbl_before.setAlignment(Qt.AlignmentFlag.AlignCenter)
        grid1.addWidget(lbl_before, 1, 0)
        lbl_cloze = QLabel("Cloze Prompts")
        lbl_cloze.setAlignment(Qt.AlignmentFlag.AlignCenter)
        grid1.addWidget(lbl_cloze, 1, 1)
        lbl_after = QLabel("Context After")
        lbl_after.setAlignment(Qt.AlignmentFlag.AlignCenter)
        grid1.addWidget(lbl_after, 1, 2)

        self.sb_before = QSpinBox()
        self.sb_before.setMinimum(-1)
        self.sb_before.setSpecialValueText("all")
        self.sb_before.setToolTip("Number of context cues before the prompt.<br>"
                                  "Set to -1/'all' to show all previous items as context")
        grid1.addWidget(self.sb_before, 2, 0)

        self.sb_cloze = QSpinBox()
        self.sb_cloze.setMinimum(1)
        self.sb_cloze.setToolTip("Number of items to prompt for per card")
        grid1.addWidget(self.sb_cloze, 2, 1)

        self.sb_after = QSpinBox()
        self.sb_after.setMinimum(-1)
        self.sb_after.setSpecialValueText("all")
        self.sb_after.setToolTip("Number of context cues after the prompt.<br>"
                                 "Set to -1/'all' to show all following items as context")
        grid1.addWidget(self.sb_after, 2, 2)

        tab1_layout.addLayout(grid1)

        # Other Cloze Generation Settings
        grid2 = QGridLayout()
        grid2.addWidget(QLabel("<b>Other Cloze Generation Settings</b>"), 0, 0, 1, 2)

        self.cb_ncf = QCheckBox("No cues for first item")
        self.cb_ncf.setToolTip("Don't provide any context cues for first cloze item")
        grid2.addWidget(self.cb_ncf, 1, 0)

        self.cb_incr = QCheckBox("Gradual build-up/-down")
        self.cb_incr.setToolTip("For notes that have multiple clozes revealed per card,<br>"
                                "gradually build up to full reveal count at the start,<br>"
                                "and vice-versa in the end")
        grid2.addWidget(self.cb_incr, 1, 1)

        self.cb_ncl = QCheckBox("No cues for last item")
        self.cb_ncl.setToolTip("Don't provide any context cues for last cloze item")
        grid2.addWidget(self.cb_ncl, 2, 0)

        self.cb_gfc = QCheckBox("Don't generate full cloze")
        self.cb_gfc.setToolTip("Disable cards that prompt you for all items at once")
        grid2.addWidget(self.cb_gfc, 2, 1)

        tab1_layout.addLayout(grid2)
        tab1_layout.addStretch()

        self.tabWidget.addTab(self.tab, "Cloze Generation")

        # Tab 2: General
        self.tab_2 = QWidget()
        tab2_layout = QVBoxLayout(self.tab_2)

        # Scheduling
        grid3 = QGridLayout()
        grid3.addWidget(QLabel("<b>Scheduling</b>"), 0, 0)

        self.cb_ns_new = QCheckBox("Override sibling-spacing for new overlapping clozes")
        self.cb_ns_new.setToolTip("Disables sibling-burying for cards generated by the add-on,<br>"
                                  "overriding whatever deck options might be set.<br>"
                                  "Only works on Anki desktop")
        grid3.addWidget(self.cb_ns_new, 1, 0)

        self.cb_ns_rev = QCheckBox("Override sibling-spacing for overlapping cloze reviews")
        self.cb_ns_rev.setToolTip("Disables sibling-burying for cards generated by the add-on,<br>"
                                  "overriding whatever deck options might be set.<br>"
                                  "Only works on Anki desktop")
        grid3.addWidget(self.cb_ns_rev, 2, 0)

        self.cb_sfc = QCheckBox("Automatically suspend full cloze cards initially")
        grid3.addWidget(self.cb_sfc, 3, 0)

        tab2_layout.addLayout(grid3)

        # Field Names
        grid4 = QGridLayout()
        grid4.addWidget(QLabel("<b>Field Names</b>"), 0, 0, 1, 3)

        grid4.addWidget(QLabel("Original"), 1, 0, 1, 2)
        self.le_og = QLineEdit()
        self.le_og.setToolTip("These fields can only be renamed through this dialog")
        grid4.addWidget(self.le_og, 1, 2)

        grid4.addWidget(QLabel("Settings"), 3, 0, 1, 2)
        self.le_st = QLineEdit()
        self.le_st.setToolTip("These fields can only be renamed through this dialog")
        grid4.addWidget(self.le_st, 3, 2)

        grid4.addWidget(QLabel("Full"), 4, 0, 1, 2)
        self.le_fl = QLineEdit()
        self.le_fl.setToolTip("These fields can only be renamed through this dialog")
        grid4.addWidget(self.le_fl, 4, 2)

        grid4.addWidget(QLabel("<b>Overlapping Cloze Note Types</b>"), 5, 0, 1, 3)
        grid4.addWidget(QLabel("Names"), 6, 0, 1, 2)
        self.le_model = QLineEdit()
        self.le_model.setToolTip("Comma-separated list of note types the add-on should be active on")
        grid4.addWidget(self.le_model, 6, 2)

        tab2_layout.addLayout(grid4)
        tab2_layout.addStretch()

        self.tabWidget.addTab(self.tab_2, "General")

        # Tab 3: About
        self.tab_3 = QWidget()
        tab3_layout = QVBoxLayout(self.tab_3)
        tab3_layout.setContentsMargins(2, 2, 2, 2)
        self.htmlAbout = QTextBrowser()
        self.htmlAbout.setOpenExternalLinks(True)
        tab3_layout.addWidget(self.htmlAbout)

        self.tabWidget.addTab(self.tab_3, "About")

        self.verticalLayout.addWidget(self.tabWidget)

        # Button box
        self.buttonBox = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok |
            QDialogButtonBox.StandardButton.Cancel |
            QDialogButtonBox.StandardButton.RestoreDefaults
        )
        self.verticalLayout.addWidget(self.buttonBox)

        self.tabWidget.setCurrentIndex(0)
